version: "3"
services:
  backend:
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    build: ./backend
    container_name: aircraft-backend
    ports:
      - "8005:8000"
    volumes:
      - "./backend/server:/opt/server"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: aircraft-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./db:/var/lib/postgresql/data"
    ports:
      - "5436:5432"