# Generated by Django 4.2.2 on 2023-10-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Helicopter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=30)),
                ("weight", models.FloatField()),
                ("fuel_capacity", models.PositiveIntegerField()),
                ("max_altitude", models.DecimalField(decimal_places=3, max_digits=3)),
                (
                    "take_off_weight",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
        ),
    ]
