# Generated by Django 4.2.2 on 2023-10-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helicopter",
            name="max_altitude",
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
